# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

# This is a reminder that you are using a generated .pro file.
# Remove it when you are finished editing this file.
message("You are running qmake on a generated .pro file. This may not work!")


TEMPLATE = subdirs
SUBDIRS += QtApplication1/QtApplication1.pro \
    QtQuickApplication1/QtQuickApplication1.pro \
    coreProfileTask1/coreProfileTask1.pro \
    coreProfileTask1/x64/Debug/qmake/temp/qtvars.pro
